export const ErrorBoundaryFallback = () => {
  return "Something went wrong. Please try again.";
};
